package:
  image:
    name: gradle:jdk11@sha256:cc14d1440058ab9c359756669a0364a5d731456fb5b6e0b7067ec9bf4a09bf28
  script:
    - gradle jar shadowjar
    - gradle -b legacy-build.gradle shadowjar
  artifacts:
    paths:
      - build/libs/keycloak-scim-1.0-SNAPSHOT.jar
      - build/libs/keycloak-scim-1.0-SNAPSHOT-all.jar
      - build/libs/keycloak-scim-1.0-SNAPSHOT-all-legacy.jar
  only:
    - main
